presentation_name = "presentation-server-stage"
application_name = "application-server-stage"
region           = "nyc1"
size             = "s-1vcpu-1gb"
image            = "ubuntu-20-04-x64"
digitalocean_token = "your-digitalocean-token"
